#!/bin/bash
#
# 00-aegis-header - the header of the MOTD.
# Seaton Jiang <hi@seatonjiang.com>
#
# The latest version of Aegis can be found at:
# https://github.com/seatonjiang/aegis
#
# Copyright (C) 2021 Seaton Jiang
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

export LC_ALL=C.UTF-8

set -u -o pipefail

# Colors
G="\033[01;32m"
N="\033[0m"

echo -e "\nYou are logged in to ${G}$(uname -n)${N}. System information as of $(/bin/date "+%Y-%m-%d %H:%M:%S").\n"
